version: "3.8"
services:
  syno-slideshow:
    build: .
    container_name: syno-photos-slideshow
    restart: unless-stopped
    ports:
      - "23535:3000" #Change outfacing port if necessary
    env_file: .env
    environment:
      - TZ=America/New_York #Change this to the same timezone you have setup on your NAS
    volumes:
      - /volume1/docker/syno-slideshow-gif/config.json:/app/config.json 
      - /volume1/docker/syno-slideshow-gif/public:/app/public
